unicef/iogt

iogt/settings/base.py
iogt/urls.py

according to the wagtail implementation guidelines `internetofgoodthings.org/en/article` schema was chosen
https://www.wagtail-localize.org/tutorial/2-configure-wagtail-localize/#urls

IU-21 | add language parameter in url

---

home/wagtail_hooks.py

Fixes #153 
- Enabled sorting for banner index page, section index page and section page

Enh/enable sort for banner index, section index, and section pages

---

iogt_users/wagtail_hooks.py

Fixes #141 
- Added registration survey response in users list export
- Only the latest submission will be included in users list export

Adds registration survey response in user export list

---

home/templates/home/tags/sub_sections.html
home/templatetags/home_tags.py

- Fixed rendering of section page
- Fixed rendering of footers

Fixes rendering issues

---

iogt/views.py

- Added quizzes URLs in sitemap API

Adds quizzes in sitemap

---

home/models.py
home/templates/home/section.html
questionnaires/templates/questionnaires/tags/quizzes_list.html
questionnaires/templatetags/questionnaires_tags.py

- Added child quizzes in section

Adds child quizzes in section page

---

home/templates/home/tags/footer.html
home/templates/home/tags/top_level_sections.html
home/templatetags/home_tags.py
iogt/templates/footer.html
iogt/templates/header.html

- Added footer pages in base
- Added top level sections in base
- Used site settings logo in header

Adds footer pages, top level sections and site settings logo

---

questionnaires/blocks.py

- Fixed checkboxes and multiselect rendering issue for quizzes and surveys

Fixes checkboxes and multiselect rendering issue

---

home/models.py

Fixed empty top level sections bug

---

questionnaires/templates/survey/survey.html

Fixes a crash on loading the survey detail page

Fix for Survey Crash

---

iogt_content_migration/README.md
iogt_content_migration/management/commands/load_v1_db.py

- Added banners in content migration (without page links)
- Added footers in content migration
- Simplify wagtail page tree fix
- Simplify index pages creation
- Made site from v1 default site

Added banners and footers content migration

---

iogt_content_migration/management/commands/load_svg.py

- Added a management command that can bulk upload SVG
- Only works if a certain folder structure is followed
```
- svg-dir
- dir1
- abc.svg
- dir2
- xyz.svg
```
- usage: `python manage.py load_svg --svg-dir <path-to-svg-dir>`

Added svg upload command

---

questionnaires/models.py

- Fixed anonymous user submission for following
- Polls
- Quizzes
- Surveys

Fixed anonymous user submission bug

---

iogt/settings/base.py
iogt/static/css/accounts.css
iogt_users/fields.py
iogt_users/forms.py
iogt_users/templates/profile.html
iogt_users/templates/profile_edit.html

Fixed issues with Profile screen

---

questionnaires/admin.py

Removed Add button from Questionnaires

---

iogt/templates/account/login.html
iogt/templates/account/signup.html

Removed placeholders

---

home/models.py

Updated Logo Help Text

---

README.md
iogt/settings/base.py

This config will be different for each deployment of IoGT.

Move wagtail-transfer config to unversioned file

---

iogt/templates/transition-page.html
locale/fr/LC_MESSAGES/django.po

Bare but sensible transition page

---

home/templatetags/home_tags.py
home/views.py
iogt/settings/base.py
iogt/templates/footer.html
iogt/templates/header.html
iogt/urls.py
questionnaires/templates/quizzes/quiz.html
questionnaires/templates/survey/survey.html
questionnaires/templates/survey/survey_landing.html

Fixes #321 
- Fixed Redirections
- Fixed hardcoded / redirections
- Fixed Login/Logout redirections

Fixed localized redirections

---

home/templates/blocks/embedded_questionnaire.html

Fixes #345 
- Fixes rendering of checkboxes in embedded mode
- Render questions label for poll and quiz in embed mode

fixes checkboxes rendering in embedded mode and render poll and quiz question 

---

questionnaires/models.py

Fixes #360 
- Polls multiselect fields like checkboxes results will be calculated based on each individual choice
- Added missing check for poll submission so results are only calculated after poll submission

separates poll results for checkboxes

---

questionnaires/forms.py

Fixes #354 
- If page break is enabled for any question without multi-step enabled, a validation error will be raised

adds validation for page break with multi step

---

home/templates/home/tags/language_switcher.html
home/templatetags/home_tags.py
iogt/templates/header.html

Localized django pages fixes

---

search/templates/search/search.html

Fix search url

---

iogt/static/css/iogt.css

fixes #381 
**Description:**
Fixed button hover state.

Fix button hover issue

---

home/templates/home/tags/language_switcher.html
home/templatetags/home_tags.py

Fixes language switcher bug

---

iogt_users/models.py

Fixed preview article bug

---

home/models.py

Fixed Section Preview

---

questionnaires/models.py
questionnaires/utils.py

fixes #407 
- fixes crash for number field submission for quiz and survey
- refactor form data handling

fixes crash for number field submission

---

questionnaires/models.py

fixes #408 
- fixes inconsistent page number during multistep form submission

fixes inconsistent step number on validation error

---

docker-compose.yml
home/processors.py
iogt/settings/base.py
iogt/templates/base.html

Added commit hash in HTML

---

search/templates/search/search.html

Fixed search page closing tag

---

home/views.py

Fixed service worker exception

---

home/templates/home/section.html
iogt/static/css/iogt.css

Added section title text

---

comments/wagtail_hooks.py

fixes #160 
- adds article title, article URL, and article locale (language code) in comments export list

adds fields to comments export

---

iogt_users/forms.py
iogt_users/templates/profile.html

Removed display name from SignUp screen

---

home/static/css/global/global.css

Fixed heading size

---

comments/templates/django_comments_xtd/reply.html
home/static/css/article/article.css
iogt/static/css/iogt.css

Fixed the Reply screen

---

iogt_users/middlewares.py
questionnaires/models.py

Fixed registration_survey to display the localized version of the survey

---

questionnaires/models.py

fixes #470 
- removed serve method for poll and used same in questionnaire abstract base class
- now anonymous user poll rendering is fixed

fixes poll serving for anonymous and logged in user

---

home/blocks.py
home/templates/blocks/embedded_questionnaire.html
questionnaires/templatetags/questionnaires_tags.py

fixes #329 
- handles multistep questionnaire as child form
- handles multistep questionnaire as embedded form

handles multistep child and embedded questionnaire

---

iogt/templates/account/logout.html
iogt/templates/account/password_change.html
iogt/templates/account/password_reset.html

Fixes #332 
The edit profile screen is disable right now, so didn't change anything to that.

Fixed styling in Account View

---

home/models.py
search/views.py

Closes #379 
Run `make update_elasticsearch_index` and then search for results

Localized Search Results

---

iogt_content_migration/management/commands/load_v1_db.py

fixes #404 
- map renamed locales to iso locales in content migrations

map renamed locales in content migration

---

home/templates/home/tags/language_switcher.html

fixes #457 
- fixes bug for language switcher for non-wagtail pages

fixes language switcher for non wagtail pages

---

messaging/views.py

fixes #506 
- user can read only his/her own threads

user can only read his/her own threads

---

iogt/templates/wagtailadmin/home/pages_for_moderation.html
iogt/templates/wagtailadmin/home/recent_edits.html

fixes #327 
- show table headers for recent edits and awaiting your review

show list headers for admin dashboard

---

home/static/css/global/global.css

fixes #459 
- fixes language picker hide behind section image

fixed dropdown visibility issues

---

home/blocks.py
home/static/css/questionnaires.css
home/templates/blocks/embedded_poll.html
home/templates/blocks/embedded_questionnaire.html
iogt/templates/account/login.html
questionnaires/models.py
questionnaires/static/css/questionnaire.css
questionnaires/static/css/survey.css
questionnaires/templates/poll/poll.html
questionnaires/templates/questionnaires/already_completed.html
questionnaires/templates/questionnaires/go_to_homepage.html
questionnaires/templates/questionnaires/login_to_participate.html
questionnaires/templates/quizzes/quiz.html
questionnaires/templates/survey/survey.html
questionnaires/templatetags/questionnaires_tags.py

fixes #471 
- for survey if already submitted without allow multiple submissions show already submitted text
- for anonymous user if login is required show button for it and on login go back to poll/survey
- for poll if already submitted without allow multiple submissions show results

display landing for questionnaires

---

messaging/views.py

fixes #571 
- start the conversation with bot will take user to chat page instead of inbox

start conversation will take to chat page

---

messaging/views.py

fixes #568 
- fixes crash on sending sms to bot

fixes crash for sending message to bot

---

home/static/css/global/global.css

fixes #370 
- show flat menu multiple times on only featured phone

show flat menu on feature phone

---

iogt/static/js/iogt.js
iogt/static/wagtaildocs/js/add-multiple.js
iogt/static/wagtaildocs/js/document-chooser-modal.js
iogt/static/wagtailimages/js/add-multiple.js
iogt/static/wagtailimages/js/image-chooser-modal.js
iogt/static/wagtailmedia/js/media-chooser-modal.js
iogt/templates/wagtaildocs/documents/edit.html
iogt/templates/wagtailimages/images/edit.html
iogt/templates/wagtailmedia/media/add.html
iogt/templates/wagtailmedia/media/edit.html

fixes #542 
- show warning on videos add/edit
- show warning on images larger than 200kb add/edit
- show warning on documents larger than 200kb add/edit

show warning of facebook free basics

---

iogt_content_migration/management/commands/load_v1_db.py

Image ID mapping for article body content

---

home/templatetags/generic_components.py

fixes #672 
- fixes crash for pages with no icon

fixes icon path not available issue

---

home/static/css/global/global.css

fixed allignment issue in footer

---

iogt_content_migration/management/commands/load_v1_db.py

Previously, no icon would display in `admin/wagtailsvg/svg/`

Fix broken loudspeaker/clipboard icon in admin view

---

iogt_content_migration/management/commands/load_v1_db.py

fixes #769 
- include unsupported tags in the post-migration report

print unsupported tags in post migration report

---

home/static/js/global/admin.js

fixes #787 
- updates css selector to uniquely identify handle for flat menu
- fixes promote tab slug help text changes

fixes promote tab slug style

---

iogt_content_migration/management/commands/load_v1_db.py

- Regular page URLs don't work when a page is in draft state.

adds admin url for pages in migration report

---

home/views.py
iogt/patch.py

- fixes fuzzy translation issue

fixes fuzzy translation issue

---

iogt_content_migration/management/commands/load_v1_db.py

sections with no live child pages are marked as draft

---

iogt_content_migration/management/commands/load_v1_db.py

fixes #811 
- translated from first_published_at date is used for translated pages

uses translated from page creation datetime for translated pages sorting

---

home/management/commands/create_initial_data.py
iogt_content_migration/management/commands/load_v1_db.py

- adds v2 domain arg for load_v1_db
- this will be set as the default site

adds v2 domain arg for load_v1_db

---

iogt_content_migration/management/commands/load_v1_db.py

fixes #849 
- keeps slug from v1 for translated pages

keeps slug from v1 for translated pages

---

home/templates/home/tags/articles_list.html
iogt/templates/generic_components/article_card.html

fixes #855 
- fixes rendering of recommended articles

fixes rendering of recommended articles

---

iogt_users/wagtail_hooks.py

partially addresses #842 
- optimizes user export query

optimizes user export query

---

iogt_content_migration/management/commands/load_v1_db.py

fixes #882 
- warning for sections with description in v1
- warning for registration survey

adds warning for sections with description

---

.github/workflows/config.yml
Makefile
cypress_tests/package-lock.json
cypress_tests/package.json
docker-compose.cypress.yml
docker-compose.test.yml
docker-compose.yml
iogt/settings/test.py
requirements.dev.txt

fixes #838 
- adds github action for django unit tests
- adds github action for cypress tests
- adds coverage report for django codebase
- artifacts (coverage report/screenshots/videos) for both actions will be available when the workflow is complete

adds github actions

---

.github/workflows/config.yml
Makefile

fixes #886 
- updates workflow of django unit tests
- adds names to artifacts for django unit tests and cypress integration tests

fixes django unit tests workflow

---

docker-compose.yml
home/management/commands/load_po_files.py
home/templates/modeladmin/translation_manager/translationentry/index.html
home/views.py
home/wagtail_hooks.py
iogt/patch.py
iogt/urls.py

do not update po files, just return translation if found in db

---

iogt_content_migration/management/commands/load_v1_db.py

fixes #909 
- adds warning to post-migration report for site settings with social media links
- adds warning to post-migration report for footers with images

warning for footers in content migration

---

iogt_content_migration/management/commands/load_v1_db.py

fixes #901 
- fixes paths for pages after content migration

fixes path after content migration

---

iogt_content_migration/management/commands/load_v1_db.py

fixes #908 
- migrate site logo
- warning for default favicon

migrate site logo and warning for default favicon

---

iogt_content_migration/management/commands/load_v1_db.py

fixes #907 
- refactor and simplify home page, site, and site settings, index pages creation
- v1 language will be respected while creating pages

respect v1 default locale in content migration

---

questionnaires/models.py
questionnaires/templatetags/questionnaires_tags.py

fixes #917 
- handles the rendering of questionnaires with no form fields as standalone and as embedded both

handles rendering of questionnaires with no form field

---

home/templatetags/home_tags.py

fixes #837 
- skip page link page as prev/next button in article

skip page link page in next and prev button

---

iogt_content_migration/management/commands/load_v1_db.py

fixes #924 
- adds warning for pages with empty image

adds warning for page with empty image

---

home/templates/home/tags/footer.html

fixes #829
- Solve translation issue for "Login/Create account" from the footer.html.

Solve translation issue for "Login/Create account"

---

comments/templates/django_comments_xtd/comment_tree.html
comments/templatetags/comment_tags.py

Fixed the like -> report bug

---

cypress_tests/cypress/integration/section/section.spec.js
home/static/css/global/global.css
home/templates/home/tags/section_featured_content_card.html

fixes #960 
- fixes test cases for section featured content

fixes test cases for featured section content

---

iogt/templates/wagtailusers/users/list.html

fixes #832
-  Add display name column

Add Display name

---

iogt/templates/base.html

fixes #952 
- fixes bottom language selector redirection issue

fixes bottom language selector redirection issue

---

iogt/static/css/iogt.css
questionnaires/templates/quizzes/quiz_landing.html
questionnaires/templatetags/questionnaires_tags.py

fixes #338 
- updates logic for answer rendering

updates logic for correct answer

---

home/static/js/global/admin.js

fixes #913 
- adds hint for stop translation

adds hint for stop translation

---

home/templates/home/tags/footer.html

fixes #682
- Add logout button in footer.

Account related links in footer

---

home/models.py
iogt/middleware.py
iogt/settings/base.py

:heavy_plus_sign: Add support for V1 migrated URLs

---

home/templates/home/tags/language_switcher.html
home/templatetags/home_tags.py
iogt/templates/translation_not_found_page.html
iogt/urls.py
iogt/views.py

:wrench: Page switcher now shows all active locales

---

home/blocks.py
home/models.py
home/templates/blocks/article.html
home/templates/blocks/page_button.html
home/templates/home/article.html
home/templates/home/home_page.html
home/templates/home/tags/articles_list.html
home/templates/home/tags/banners_list.html
home/templates/home/tags/child_pages.html
home/templates/home/tags/footer.html
home/templates/home/tags/top_level_sections.html
home/templatetags/generic_components.py
home/templatetags/home_tags.py
iogt/templates/generic_components/article_card.html
iogt/templates/generic_components/questionnaire_card.html
iogt/templates/generic_components/section_card.html
iogt_content_migration/management/commands/load_v1_db.py
questionnaires/templates/questionnaires/tags/embedded_poll.html
questionnaires/templates/questionnaires/tags/embedded_questionnaire.html
questionnaires/templates/questionnaires/tags/index_page_description_lines.html
questionnaires/templates/questionnaires/tags/questionnaire_wrapper.html
questionnaires/templatetags/questionnaires_tags.py

fixes #985 
- homepage
- banners: have valid page, must be live
- featured content
- article: have valid page, must be live
- page button: have valid page, must be live
- embedded questionnaire: have valid page, must be live
- section
- page link page: have valid page, must be live
- section: must be live
- article: must be live
- poll: must be live both in direct and card mode
- survey: must be live both in direct and card mode
- quiz: must be live both in direct and card mode
- top level sections: must be live
- article
- poll: must be live both in direct and card mode
- survey: must be live both in direct and card mode
- quiz: must be live both in direct and card mode
- page button: have valid page, must be live
- recommended articles: have valid page, must be live
- footers
- page …

fixed live/deleted content rendering

---

iogt_content_migration/management/commands/load_v1_db.py

fixes #931 
- fixes media file paths 
- fixes document file paths
- fixes thumbnail for media file paths

updates media file paths

---

questionnaires/templates/questionnaires/tags/embedded_poll.html
questionnaires/templates/questionnaires/tags/embedded_questionnaire.html

fixes #977 
- render embedded questionnaires description in
- home page featured content
- article body

renders embedded questionnaires description

---

search/templates/search/search.html

removes invalid section.css import

---

questionnaires/templatetags/questionnaires_tags.py
search/templates/search/search.html
search/templates/search/tags/search_result_cards.html

fixes #1021 
- show search results

show results for search

---

iogt_content_migration/management/commands/load_v1_db.py

fixes #1017 
- adds warning for banners with external link in post content migration report

adds warning for external link for banners in content migration

---

iogt_content_migration/management/commands/load_v1_db.py

fixes #1027 
- adds warning for featured in latest

adds warning for featured in latest

---

home/processors.py
iogt/settings/base.py
iogt/templates/base.html
iogt/templates/footer.html

fixes #976 
- for transition page don't render footer

do not show footers on transition page

---

home/management/commands/create_default_site.py

:wrench: Update create_default_site command

---

iogt/middleware.py

fixes #1035 
- use permanent redirection for v1 to v2 page map

use permanent redirect for v1 to v2 page map

---

questionnaires/templates/questionnaires/tags/already_completed.html

fixes #822
- Edit multiple attempts error message.
- Use quiz, poll and survey for multiple attempts error message.

Use quiz, poll and survey for multiple attempts error message

---

iogt_content_migration/management/commands/load_v1_users.py

In user migration, warn if a comment has been flagged which is missing from the DB

Fix user migration crash

---

home/models.py

fixes #1003 
- skip page-link-page with draft page while footer rendering

skip plp with draft page

---

home/models.py

- new footer page can't be added after this

removes adding of new footer

---

iogt/settings/base.py

Closes #1084 
- added wagtail transfer update related models setting

adds wagtailtransfer update related models setting

---

questionnaires/edit_handlers.py
questionnaires/models.py
questionnaires/views.py
questionnaires/wagtail_hooks.py

Closes #1102 
- filter out registration surveys from "Form Data" questionnaires listing

filter out registration survey from form data listing

---

comments/templates/django_comments_xtd/base.html

Closes #1113 
- removed article.css import

removes article css import

---

iogt/patch.py

Closes #1121 
- do not update if translation exists for the translation manager

do not update if translation exist in translation manager

---

cypress_tests/cypress/integration/articles/articles_chatbot.spec.js

fixes #1098
- fixes cypress failing test cases

fixes chatbot cypress tests

---

iogt_content_migration/management/commands/load_v1_db.py

Extension of #1106
Closes #1087

Migrate v1 list as v2 markdown (updated)

---

home/static/css/questionnaires.css
questionnaires/static/css/survey.css
questionnaires/templates/questionnaires/tags/embedded_poll.html
questionnaires/templates/questionnaires/tags/embedded_questionnaire.html
questionnaires/templates/questionnaires/tags/submit_button.html
questionnaires/templates/quizzes/quiz.html
questionnaires/templates/quizzes/quiz_landing.html
questionnaires/templates/survey/survey.html

Closes #995 
- unify rendering for submit/next button for poll, survey, and quiz
- render next in case of multistep in embedded mode

unify questionnaires submit next button rendering

---

home/templates/home/article.html
home/templates/home/tags/previous-next-buttons.html

Closes #994 
- fixed next and previous navigation buttons for article

fixes article sibling navigation rendering

---

home/templates/blocks/offline_app_button.html

fixes #792
- fixes rendering of download app for offline access button

fixes download app button rendering

---

home/static/css/global/global.css
iogt/templates/base.html

Closes #758 
- used 3.7% left and right margin for the central column at all screen sizes

use percentage margin for central column

---

Makefile
cypress_tests/cypress/integration/articles/articles.spec.js
cypress_tests/cypress/integration/articles/articles_navigation_buttons.spec.js
cypress_tests/cypress/integration/common/common_texts.spec.js
cypress_tests/cypress/integration/common/direct_display.spec.js
cypress_tests/cypress/integration/common/direct_display_multipage_survey_and_quiz.spec.js
cypress_tests/cypress/integration/common/embed_with_article.spec.js
cypress_tests/cypress/integration/common/embedded_article_with_multipage_survey_and_quiz.spec.js
cypress_tests/cypress/integration/polls/polls_with_checkboxes.spec.js
cypress_tests/cypress/integration/polls/polls_with_radio.spec.js
cypress_tests/cypress/integration/quiz/quiz_with_anonymous_user.spec.js
cypress_tests/cypress/integration/section/section.spec.js
cypress_tests/cypress/integration/section/section_related_articles.spec.js
cypress_tests/cypress/integration/section/section_subsections.spec.js
cypress_tests/cypress/integration/survey/survey.spec.js
cypress_tests/cypress/integration/survey/survey_with_2_pages.spec.js
cypress_tests/cypress/integration/survey/survey_with_anonymous_user.spec.js
cypress_tests/cypress/integration/survey/survey_with_skip_logic.spec.js
cypress_tests/package-lock.json
docker-compose.cypress.yml
docker-compose.test.yml

Intention is to re-enable failing tests as soon as possible.

Skip failing cypress tests

---

home/image_formats.py

Closes #1162 
- adds original image format

adds original image format

---

iogt/settings/base.py

Closes #1183 
- added `username` in wagtail transfer lookup fields

adds wagtail transfer lookup fields

---

iogt_content_migration/management/commands/load_v1_db.py

Closes #1208 
- fixes slug validation error

fixes slug duplication issue

---

iogt/settings/base.py

Closes #1232 
- adds Bengali lang. support

adds bn lang support

---

cypress_tests/cypress/integration/articles/articles_comments.spec.js
cypress_tests/cypress/integration/footers/navbar.spec.js

Have added some tests around users making comments

Adding new tests

---

iogt/templates/account/password_change.html

Remove Forgot PIN button in password reset

---

home/models.py
home/templates/home/tags/banners_list.html

Closes #1018 
- allow decorative banners to render
- banners without linked page and just image will render too

adds decorative banners without link and just image

---

home/blocks.py

Closes #1237 
- fix audio/video download link

fixes audio video download

---

iogt_content_migration/management/commands/load_v1_db.py

Remove article subtitle during migration

---

home/static/js/global/admin.js

Closes #1234 
- Show warning message for download data for group permission

show warning of download data permission for group

---

cypress_tests/cypress/integration/articles/page_link_page_articles.spec.js
home/static/css/global/global.css
iogt/templates/generic_components/section_card.html

Closes #1032 
- fixes section card title and image width inconsistency
- fixes section card title font size inconsistency

makes section card width and font sizes consistent on different screen widths

---

docker-compose.yml
home/templatetags/generic_components.py
iogt/settings/base.py
iogt/templates/wagtailadmin/shared/menu_settings_menu_item.html

Closes #911 
- adds site version

adds site version

---

iogt/templates/wagtailusers/groups/includes/formatted_permissions.html

Closes #1347 
- filter out "User" and "Group" permission from admin panel

filter out user and group permissions

---

home/templatetags/generic_components.py
home/test.py

- fixes utm params parsing 
- fixes query params format

updates query params formatting and utm params parsing

---

questionnaires/templates/poll/poll.html
questionnaires/templates/questionnaires/tags/embedded_poll.html
questionnaires/templates/questionnaires/tags/embedded_questionnaire.html
questionnaires/templates/questionnaires/tags/field_description.html
questionnaires/templates/quizzes/quiz.html
questionnaires/templates/survey/survey.html

show optional + given help text for question

---

iogt/static/js/sw-init.js

#1388 
- temporarily disable push notifications until a user-initiated subscription is implemented

disable fe push notification subscription

---

docker-compose.cypress.yml
docker-compose.selenium.yml
docker-compose.test.yml
docker-compose.yml
iogt/settings/base.py
iogt/static/js/sw-init.js
iogt/templates/base.html
notifications/processors.py
notifications/wagtail_hooks.py

- make push notification feature configurable
- depending upon env. var push notification feature will be enabled or disabled
- add env. var `PUSH_NOTIFICATION`
- default is `disable`
- set `enable` to test push notifications

makes notification feature configurable

---

iogt/templates/wagtailusers/groups/includes/formatted_permissions.html

All permissions are added in Groups

---

notifications/README.md

Let me know if anything is missing or incorrect.

Update readme for notifications

---

docker-compose.yml
docs/cache.md
iogt/settings/base.py
requirements.txt

Introduces wagtail-cache to provide page caching. See documentation at 'docs/cache.md'.

Install wagtail-cache

---

home/static/css/global/global.css
home/templates/home/section.html
iogt/static/css/iogt.css
iogt/templates/generic_components/article_card.html
iogt/templates/generic_components/section_card.html

Closes #1469 
- Title will take 100% width when the lead image isn't available for section, article in section listing and home page featured content.

Extended paragraph width 100% conditionally

---

docker-compose.selenium.yml
requirements.dev.txt
selenium_tests/base.py
selenium_tests/homepage/test_layout.py
selenium_tests/pages.py
selenium_tests/questionnaires_all/test_questionnaire_inputs.py

Was looking to add some test around relative location of elements and this is easily done in Selenium 4, so have upgraded references to Selenium 4. Have included a basic relative location test for now but scope to increase coverage, need to consider how best to sample different configurations, @istride can discuss in our catch up

Moving to selenium 4 and adding layout tests

---

README.md
docs/cache.md

Updated documentation, with link from the main readme.

Documentation for page cache

---

home/static/css/global/global.css

Closes #986 
- Page Link Page title aligned on Section Page

Page Link Page title align on Section Page

---

home/static/css/global/global.css

Closes #1370 
- Fixes search icon stretch

fixes search icon stretch

---

requirements.txt

Fix wagtailmenus package to a stable version

---

iogt/urls.py

Make API docs publicly accessible

---

questionnaires/superset/README.md
requirements.txt

updates superset readme to add instructions to share dashboard

---

home/templatetags/generic_components.py
home/wagtail_hooks.py
iogt/settings/production.py
iogt/templates/wagtailadmin/shared/menu_settings_menu_item.html
requirements.dev.txt
requirements.in
requirements.txt

Upgrade to Wagtail 2.16.3

---

questionnaires/api/v1/serializers.py
questionnaires/api/v1/tests.py
questionnaires/views.py

Form data is a JSONField, which does the conversion automatically.
Closes #1688

Stop explicitly converting form data to/from JSON

---

iogt/settings/base.py

Prevents an error being raised when uploading SVGs.

Set SVG upload folder

---

home/templates/wagtailimages/images/edit.html

showing information while edit image title

discription added for image title as alt text

---

home/views.py
iogt/static/js/idb.js
iogt/static/js/iogt-no-jquery.js
iogt/static/js/iogt.js
iogt/static/js/sw-init.js
iogt/templates/base.html
iogt/templates/sw.js
questionnaires/templates/questionnaires/tags/submit_button.html

1. Fix for iOS offline pages because iOS does not support BackgroundSyncManager
2. Changed the alert messages as toast notifications

Offline pages ios fix
