unicef/iogt

home/models.py
home/templates/home/tags/footer.html
home/templatetags/home_tags.py
iogt/static/css/footer.css
iogt/templates/base.html

Related to issue #19 . A fully editable footer snippet that allows changes to navigation links, logos and the "essential" links to privacy policy, terms of use, etc. All links are to pages within the site.

add editable footer snippet

---

Dockerfile.dev
docker-compose.yml

Installing psycopg2 needed libpq-dev python3-dev and build-essential. Since this is just the development setup, keeping it simple and not installing them explicitly

Minor housekeeping

---

iogt/settings/base.py
requirements.txt

`wagtail-localize` has all of the capabilities that we should need for managing language translation (see [overview video](https://www.youtube.com/watch?v=mEzQcOMUzoc)).
If additional tools are needed in the translation workflow then we can convert the `.po` files that are used by Wagtail and Django into other formats.  Users who work directly with `.po` files (instead of using the Wagtail admin interface) could install and use [Poedit](https://poedit.net/).

Add wagtail-localize

---

home/templates/home/tags/articles_list.html
home/templates/home/tags/featured_content_list.html
home/templates/home/tags/sub_sections.html

The section and sub-section information was hard-coded in templates.  This PR comments the hard-coded information until this is fixed properly as part of the site redesign.  There is currently some duplication in the templates that can also be addresses with the redesign.

Comment hard-coded section information

---

external_links/middleware.py
iogt/settings/base.py

When `RewriteExternalLinksMiddleware` is enabled in `settings.py` each `text/html` response is checked for links as the page is rendered with all external links being rewritten on-the-fly.
Fixes #4

Handle external links using middleware

---

iogt/settings/base.py
iogt/templates/header.html

`Admin > Settings > Flat Menus` can now be used to create language-specific top-level menus for each required language.
When templates are rendered, the current language code will be automatically detected - this language code is then used to display the correct menu.
In order for the correct menu to be chosen, the menu's `Handle` must be set to `en_menu_live` for English, `fr_menu_live` for French, etc.
Only the overall menu requires the `Handle` to be set, the individual menu items within a menu do not require a `Handle` value.
This PR also disables (hides) Wagtail's standard "Main Menu" option from `Admin > Settings` to avoid confusion.
Resolves 137, resolves 144.

Add language-specific menus using flat menus

---

.gitignore

`.mo` files are created during the build process using `./manage.py compilemessages`

Update .gitignore to exclude compiled translations

---

iogt/static/manifest/manifest.webmanifest
iogt/templates/sw.js

- Uses sitemap API to fetch URLs to use in precache
- All Pages (homepage, sections, articles, footers, polls, surveys, quizzes) will be cached

Register urls for precache

---

iogt/templates/base.html

Adds traditional Universal Analytics (UA) and Google Analytics 4 (GA4) tracking to `base.html` at the same time as per documentation [here](https://developers.google.com/analytics/devguides/collection/ga4/basic-tag?technology=gtagjs).
The settings page already allows the local site and overall global tracking UA and GA4 properties to all be entered.
Resolves #22

Add code for Google Analytics

---

home/management/commands/fix_misplaced_sections.py

Some sections have been misplaced as part of the initial data entry. This command will fix their placement to be direct children of the SectionIndexPage.

Fix misplaced sections placement

---

comments/templates/django_comments_xtd/comment_tree.html

Fixes #308 
-  It is possible to report one's owns comments, is that intentional?
- Double check the text to be displayed for reported comments: For moderators, {% blocktrans count counter=item.flagged_count %}A user has flagged this comment as inappropriate. {% plural %}{{ counter }} users have flagged this comment as inappropriate.{% endblocktrans %} or Reported by {{ item.flagged_count }} (the latter is currently used)? For users, This is a reported comment is the current text.

Fixed reporting issues

---

home/models.py
questionnaires/templates/questionnaires/tags/polls_list.html
questionnaires/templates/questionnaires/tags/quizzes_list.html
questionnaires/templates/questionnaires/tags/surveys_list.html
questionnaires/templatetags/questionnaires_tags.py

Fixes Direct Display from #6 
As part of this ticket, the section screens will now respect the direct_display flag. If that is set to `True`, a form will be rendered

Added direct display to Questionnaires

---

iogt_content_migration/management/commands/load_v1_db.py

Fixes #337 
- Added a skip-locales flag to load_v1_db management command
- Data of locales other than Default locale will be filtered out by giving above-mentioned flag

adds a skip locales flag to load v1 db command

---

questionnaires/templates/poll/poll.html
questionnaires/templates/quizzes/quiz.html
questionnaires/templates/survey/survey.html

Fixes #364 
- removes back button on start page of poll, quiz, and survey
- fixes broken rendering of quiz and survey due to missing template tag

removes back button on start page of poll, quiz, and survey

---

questionnaires/forms.py

Fixes #383 
- raises validation error when user skip to a question with in-between required fields
- e.g., Q1, Q2 (required), Q2, and Q1 skips to Q3 then validation error will be raise.

adds validation for skipping questions for required in-between questions

---

home/wagtail_hooks.py

fixes #143 
- Adds help text to "Redirect from" field in Redirects form

adds help text to redirect from field

---

comments/wagtail_hooks.py

fixes #158 
- adds a view live column to comments listing
- it will open the associated page in a new tab

adds page live link in comments listing

---

comments/wagtail_hooks.py
iogt/settings/base.py
iogt_users/wagtail_hooks.py
questionnaires/models.py
questionnaires/views.py

fixes #161 
- updates export filename for comments to `comments_timestamp`
- updates export filename for users to `user_timestamp`
- updates export filename for poll to `poll-poll_title_timestamp`
- updates export filename for survey to `survey-survey_title_timestamp`
- updates export filename for quiz to `quiz-quiz_title_timestamp`

updates export filename for users, comments, quiz, poll, and survey

---

iogt_users/wagtail_hooks.py

fixes #182 
- handles registration survey response in user export for multi-lang
- export will include the very first submission

handles registration survey response in user export for multi-lang

---

iogt_content_migration/management/commands/load_v1_db.py

Fix: Migrating DBs with ch/sho locales would create these in our DB, but there they are invalid (renamed to ny/sn) and crash the page
Fix: Migration would crash for surveys with images.

Fix locale mapping

---

messaging/templates/messaging/thread_detail.html

fixes #507 
- fixes left menu misplaced issue on thread details page

fixes left menu misplaced issue on chat ui

---

iogt/templates/base.html

fixes #581 
- removes google material icons stylesheet as not being used anywhere in the project

removes google fonts stylesheet as not being used

---

iogt_users/forms.py

Closes #654 
Prior to making changes for this I noted that from the iogt app, a user can NOT register a new user with a username that differs only in terms of case. For example, I created a user foobar:
---
---
I then attempted to create a user FoObAr, and was refused with the following validation message:
---
But, a user CAN do it from the Wagtail admin interface. This change adds validation to `WagtailAdminUserCreateForm` to mirror the above behavior:

Prevent new user registrations that differ only in capitalization

---

home/static/css/section/section.css

Fixes #707 
Small style tweak fixes this on both related articles and sub sections:
I confirmed that the "completed" overlay still renders properly, which seems to be the primary function of the style I modified:
I did have one question -- There exists a sass file section.scss containing section styles, but it appears that recent changes only update the .css version, so that's what I did here. Is this correct?

Fix image clipping on section pages at mobile size

---

home/models.py
home/utils/image.py

Fixes #719 
In `SVGToPNGMap.get_png_image()`, a scaling factor of 10 is being passed to `convert_svg_to_png_bytes()`, resulting in a 10x scaling of the resulting png image when that scale value is passed to `cairosvg.svg2png()`. Additionally, the default scale value in `convert_svg_to_png_bytes()` is 100, which would result in a 100x scaling. Setting this to 1 results in a png that is the same width and height as the source svg.
As an example, I downloaded a [freely available svg file](https://www.svgrepo.com/svg/365021/aperture-thin) which has a defined width and height of 256px. I uploaded it into the iogt app before and after making this change. The below screenshot shows that before making this change, the resulting png is scaled 10x, or 2560x2560 px (195 kB):
---
Whereas after this …

Fix scaling factor when calling cairosvg.svg2png

---

home/models.py
iogt_content_migration/management/commands/load_v1_db.py

fixes #793 
- adds migration of related articles in section
- these will be added as page link page
- updates section to render these page link pages with articles
- if there are null entries then show in post-migration report

adds migration for related section for articles

---

iogt_content_migration/management/commands/load_v1_db.py

`featured_in_homepage_start_date` is ignored for translated articles, only the entry of the corresponding English article counts.

Fix featured content for non-English homepages

---

comments/forms.py
comments/templates/comment_reply.html
comments/templates/django_comments_xtd/comment_tree.html
comments/templates/django_comments_xtd/reply.html

fixes #834 
- updates rendering check for anonymous user_name for comment 
- 'anonymous' and 'Anonymous' will be treated as same
- V2 will save capitalized 'Anonymous'

anonymous username for comment irrespective of case

---

home/management/commands/sync_translated_pages.py

Fixes #868
- created a management command to sync translated pages
- added a --publish flag to automatically publish after synchronization
usage:
- `python manage.py sync_translated_pages`
- `python manage.py sync_translated_pages --publish`

creates a management command to sync translated pages

---

iogt_content_migration/management/commands/load_v1_db.py

fixes #923 
- uses 443 as port for site object
- uses the first value of --v1-domains as the hostname for site object

set port and hostname in content migration

---

home/mixins.py
home/models.py
home/static/css/global/global.css
home/templates/home/section.html
home/templates/home/tags/section_featured_content_card.html
home/templatetags/image_tags.py

fixes #710 
- updates UI for section featured content
- lead image of featured content will be displayed
- section font color will be used as svg icon and right angle bracket stroke color

updates ui for section featured content

---

iogt_content_migration/management/commands/load_v1_db.py

fixes #968 
- create locale details in content migration
- all locale details will be active by default
- main language will be set from v1 db

create locale details in content migration

---

home/models.py

fixes #964 
- model cluster has limitations for related object traversal [see [here](https://github.com/wagtail/django-modelcluster/issues/82)]
- refactor code to implement filters in python instead of DB
- fixed section and article preview mode

refactor to handle model cluster field in preview of page

---

iogt/settings/base.py
iogt/urls.py
requirements.txt

fixes #890 
- adds django-health-check package with db, cache, storage, migration apps
- register url as `/health-check/` 
sample request:
`curl -H "Accept: application/json" http://localhost:8000/health-check/`
sample response:
`{"Cache backend: default": "working", "DatabaseBackend": "working", "DefaultFileStorageHealthCheck": "working", "MigrationsHealthCheck": "working"}`

adds health check package

---

questionnaires/templates/quizzes/quiz_landing.html
questionnaires/templatetags/questionnaires_tags.py

fixes #338 
- used [aria-label](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label) for accessibility as span tag doesn't have any alt text option

adds accessibility text for quiz answers

---

home/static/css/global/global.css
iogt/templates/nav_bar.html

Closes #1071 
- center align text for flat menu item

fixes menu item text alignment

---

questionnaires/management/commands/fix_survey_skip_logic.py

- if survey skip-logic doesn't have a survey key then it shouldn't crash the management command

handles case of no survey key in skip logic

---

home/wagtail_hooks.py

Closes #1164 
- removes register richtext features hook
- middleware becomes the single source of truth to convert external URLs to an intermediate page URL

removes register richtext features hook to make middleware source of truth for external urls

---

iogt_content_migration/management/commands/load_v1_db.py

Closes #1220 
- sets larger image for the top section to false and adds message in the post-migration report
- disable comments for all pages (section, article) and adds message in post-migration report

update content migration for large image for top section and comments

---

home/templates/home/tags/language_switcher.html
home/templatetags/home_tags.py

An exception was occurring when getting language info for locales in the database where the locale language is not configured in the `LANGUAGES` and/or `EXTRA_LANG_INFO` setting. I have chosen to silently skip any locale that has this problem.
Closes #1214

Allow the language switcher to gracefully handle missing languages

---

iogt_content_migration/management/commands/load_v1_db.py

Closes #1258 
- In V1 we get translated pages info from the `core_pagetranslation` table, something like following
- translated from page id, translated page id
- but in SA backup, some rows in this table contain the same value for both columns
- this is messing up the migration script 
- fix: skip translated page if it has the same page id as translated from page id

skip translated page with same page id

---

iogt/patch.py

Closes #1249 
- Patched the block translate rendering to try and use database-backed translation first
- if not found in the database then revert to the default behavior

fixes block translation to load from translation entity

---

home/blocks.py
iogt/views.py

Closes #1314 
- stopped pre-loading of audio/video assets

don't preload media (audio/video) assets on page load

---

questionnaires/views.py

- we were including the user name and page URL in export
- for each user submission 2 additional queries were executed 
- 1 for user and 1 for page
- pre-fetch both user and page with the user submission
- reduced complexity from O(n) to O(1)
e.g., for 2000 user submissions
- before optimization
1 query for user submissions
2000 queries for users
2000 queries for pages
- after optimization
1 query for user submission with pre-fetch of users and pages

optimize user submission data export

---

iogt/settings/base.py
iogt/tests.py
iogt/utils.py
iogt/views.py

- django's `static()` function relies on static files manifest
- django's `static()` function accepts the normal file path and returns the hash attached URL
- previously I was passing md5 attached file in `static()` and it was throwing an error
- now only pass normal files to `static()` and filter out md5 attached files

filter out already md5 generated files as static return those

---

questionnaires/tests.py
questionnaires/views.py

- questionnaires having submissions of deleted questions can't be exported
- uses clean name for deleted questions in export

gracefully handle change of questions which already has submissions

---

iogt/static/js/iogt.js

Closes #1400 
- don't show a double menu for JavaScript enabled devices
for chrome one can enable/disable JS as follows

hides double menu for js enabled devices

---

comments/static/css/report-page/report-page.css
comments/static/css/report-page/report-page.scss
home/static/css/global/global.css
iogt/static/css/chatbot.css
iogt/static/css/footer/footer.css
iogt/static/css/footer/footer.scss
iogt/static/css/header/header.css
iogt/static/css/header/header.scss
iogt/static/css/iogt.css

Closes #1399 
- update font-family order
- if Poppins doesn't support glyphs then "Open Sans" will take over
- reference: https://developer.mozilla.org/en-US/docs/Web/CSS/font-family

fixes font family order

---

requirements.txt

drf-yasg still uses 'NullBooleanField' from djangorestframework, which was deprecated and has now been removed.
This was causing the tests to fail.

Hold djangorestframework at v3.13.x due to breaking change

---

README.md
iogt/settings/base.py
iogt/settings/docker_compose_dev.py
questionnaires/api/v1/views.py

Closes #1447 
- DRF permissions were added globally on all APIs including the wagtail transfer
- remove global DRF permissions and limit those to specific questionnaire APIs
- removes wagtail transfer config from `docker_compose_dev.py`, not needed
- update readme for wagtail transfer

fix permission issue for wagtail transfer

---

home/wagtail_hooks.py

Closes #1496 
- Adds "SORT CHILD PAGES" button alongside page buttons

adds sort child pages button

---

home/models.py

Closes #1497 
- Recommend content field was missing from content panel list
- Added it to content panel list in article

fixes article content panel

---

iogt/static/js/iogt.js
iogt/templates/footer.html

Closes #1506 
- There was a requirement to hide the double header (search and language dropdown) for JS-enabled devices see #1400 
- Due to the structure of the HTML this change broke the "Menu" button as the Menu button was connected to the double header which is hidden for JS-enabled devices now
- Restructure the HTML and make double header independent of it.

fixes html structure for menu

---

requirements.txt

Closes #1508 
- For wagtail >= 2.13 an incompatibility for tabbed interface in chooser panel was introduced see [here](https://github.com/torchbox/wagtailmedia/releases/tag/v0.7.1)
- Updates wagtailmedia package in which this issue has been fixed

updates wagtailmedia version

---

home/static/css/global/global.css

Closes #1578
- Child Section Pages in the list have images that are aligned with other Page types.

Fix alignment issue for images on child Section Pages in Section Pages List

---

docs/cache.md
iogt/settings/base.py

At the moment, page caching (and other caching features) rely on having a single Redis server or cluster available for exclusive use by a single IoGT instance. In large deployments of IoGT, this situation would become quite time-consuming to manage. It would be useful to have the option to allow several instances of IoGT to share a single Redis instance.
The main problem is that Redis doesn't offer very robust options for sharing between multiple clients (apps). Redis does support multiple databases, but only up to 16, and Redis Cluster doesn't support multiple databases at all. The best that can be done is to partition the key space with a prefix, for each client that shares a Redis instance, to make sure that different clients don't interfere with one another. This partitioning method …

Introduce cache key prefix configuration env var

---

iogt/settings/base.py

Closes #1599 
It explicitly defines the datetime format for Django Rest Framework (DRF) as "%Y-%m-%dT%H:%M:%S.%fZ" to ensure consistency in the format of datetime objects across the application. This ensures that our datetime objects are always formatted consistently

Explicitly define datetime format for API

---

home/tests/tests.py
questionnaires/api/v1/tests.py

There are repeated warnings about the BeautifulSoup HTML parser appearing in the logs while the unit tests are running. The warnings might obscure more important problems that may occur during test runs. The fix is simply to specify exactly which parser to use - I have set it to 'lxml'.

Reduce number of warning messages in test logs

---

.github/workflows/config.yml
Dockerfile.dev
Makefile
README.md
docker-compose.selenium.yml
iogt/settings/test.py
requirements.dev.txt
selenium_tests/README.md
selenium_tests/base.py

This PR allows test to be run in several processes at the same time, which substantially reduces the amount of time required to run a full test suite - especially Selenium tests.
Several improvements were required to make this possible:
- Run Selenium tests against a PostgreSQL database instead of SQLite
- Allow several test servers to be started by the Selenium test suite
- Introduce an env var to control parallelism
Even if the tests are not run in parallel, the Selenium tests should be more stable now due to the use of PostgreSQL - tests were failing randomly due to not being able to flush the SQLite database.

Allow unit and selenium tests to run in parallel

---

home/management/commands/check_multiple_translation_sources.py
iogt/settings/base.py
requirements.txt

Closes #1604
- **Command**: python manage.py check_multiple_translation_sources
- Django: 3.2.0
- wagtail-localize: 1.3.3
- Default auto field added in settings

Fix translating a page - MultipleObjectsReturned

---

iogt/settings/base.py
matomo/templates/matomo_tracking_tags.html
matomo/templatetags/matomo_tags.py
matomo/tests/test_matomo_tags.py

The purpose of this feature is to allow tracking of the same site to two different site IDs in Matomo. This is deemed necessary to emulate what was occurring with Google Analytics before the migration to Matomo. Each site is tracked individually via its own site ID and in aggregate with other sites via a 'global' site ID. The global site ID tracks metrics from all sites to allow an overview for IoGT project management, whereas the individual site ID is for UNICEF country offices to view the metrics from their own site only.

Track additional site ID with Matomo

---

iogt/settings/base.py
matomo/templates/matomo_tracking_tags.html
matomo/templatetags/matomo_tags.py
matomo/tests/test_matomo_tags.py

When JavaScript is disabled in the browser, we use the Matomo Image Tracker to gather analytics data. In this case, first party cookies are also disabled and Matomo is not able to differentiate between different visitors very well. The tracking ID is intended to provide the same function as the visitor ID that is usually provided by Matomo when JS is enabled.

Create session-based user tracking ID

---

comments/templates/comments/community_moderation.html
iogt/static/css/iogt.css

Include the entire text of comments in Community Comment Moderation, and link to the comments. Issue #1602 resolved.

Show entire comment to community moderators

---

messaging/templates/messaging/tags/chatbot_auth_tokens.html

Resolving issue #1614. The chatbot token is now hidden with a click to reveal functionality.

Hide chatbot authentication string

---

comments/templates/comments/community_moderation.html
iogt/static/css/iogt.css

Response to comment in #1658 :
>For this I would rather have the link to the comment not sympathetic, actually, so that it is clear that the Actions are comment moderation actions. Could we keep the button, change the text to "View Comment", and put it centered underneath the text?

Adjust location of 'view comment' link in CCM UI

---

iogt/settings/base.py
iogt/settings/production.py
requirements.dev.txt
requirements.in
requirements.txt

The recent upgrade to Wagtail v3 is incompatible with the currently used version of wagtail-transfer (v0.8.3). Upgrading wagtail-transfer will fix the incompatibility.
Resolves #1684

Upgrade wagtail-transfer to v0.8.5
